### ISSUE TITLE
get_links() should refrain from putting questionable links into the queue - downloader() should also filter them out

### ISSUE THREAD

**Issue by randomshinichi** [randomshinichi/geminiscraper#1]
.xml, .jpg, .mp4 etc

**Comment by randomshinichi** [comment]
```
RROR - gemini://nytpu.com/gemlog/files/tape-deck.mp4 failed@get_links() parsing page: Any { .. }
WARN - gemini://gem.1.21jiggawatts.net/posts/2020-07-28-the-future-internet.gmi failed: IO error: Connection refused (os error 111)
WARN - gemini://gem.1.21jiggawatts.net/posts/2020-07-16-new-york.gmi failed: IO error: Connection refused (os error 111)thread '<unnamed>' panicked at 'Invalid state: ListWaitForSpace', /home/shinichi/.cargo/registry/src/github.com-1ecc6299db9ec823/gmi-0.2.1/src/gemtext.rs:305:18
ERROR - gemini://cosmic.voyage/rss.xml failed@get_links() parsing page: Any { .. }
thread '<unnamed>' panicked at 'Invalid state: ListWaitForSpace', /home/shinichi/.cargo/registry/src/github.com-1ecc6299db9ec823/gmi-0.2.1/src/gemtext.rs:305:18
ERROR - gemini://cosmic.voyage/atom.xml failed@get_links() parsing page: Any { .. }
thread '<unnamed>' panicked at 'Invalid state: ListWaitForSpace', /home/shinichi/.cargo/registry/src/github.com-1ecc6299db9ec823/gmi-0.2.1/src/gemtext.rs:305:18
ERROR - gemini://cosmic.voyage/HMS%20Inkredible/scan0001.txt failed@get_links() parsing page: Any { .. }
thread '<unnamed>' panicked at 'Invalid state: ListWaitForSpace', /home/shinichi/.cargo/registry/src/github.com-1ecc6299db9ec823/gmi-0.2.1/src/gemtext.rs:305:18
ERROR - gemini://cosmic.voyage/HMS%20Inkredible/log0003.txt failed@get_links() parsing page: Any { .. }
thread '<unnamed>' panicked at 'Invalid state: ListWaitForSpace', /home/shinichi/.cargo/registry/src/github.com-1ecc6299db9ec823/gmi-0.2.1/src/gemtext.rs:305:18
ERROR - gemini://cosmic.voyage/HMS%20Inkredible/log0002.txt failed@get_links() parsing page: Any { .. }
thread '<unnamed>' panicked at 'Invalid state: ListWaitForSpace', /home/shinichi/.cargo/registry/src/github.com-1ecc6299db9ec823/gmi-0.2.1/src/gemtext.rs:305:18
ERROR - gemini://cosmic.voyage/HMS%20Inkredible/log0001.txt failed@get_links() parsing page: Any { .. }
WARN - gemini://typed-hole.orgfinger//@typed-hole.org failed: IO error: failed to lookup address information: Name or service not known
WARN - gemini://typed-hole.org/project_gemini.jpg failed: Response parse error: Error parsing response! The response's header was invalidWARN - gemini://zaibatsu.circumlunar.space/~solderpunk/ failed: IO error: Network is unreachable (os error 101)
WARN - gemini://makeworld.gq/gemlog/2020-05-21-first.gmi failed: IO error: failed to lookup address information: Name or service not known
thread '<unnamed>' panicked at 'url couldn't be parsed: AuthorityParseError(MissingHost)', src/gemini.rs:25:56
ERROR - gemini://geddit.pitr.ca failed@get_links() parsing page: Any { .. }WARN - gemini://en.gmn.clttr.info/cgmnlm.gmi failed: IO error: failed to lookup address information: Name or service not knownERROR - TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: AccessDenied,
}
WARN - gemini://ella.wantscuddl.es/gemini-syntax-highlighting-for-kate.xml failed: IO error: received fatal alert: AccessDenied
WARN - gemini://git.fkfd.me/ failed: IO error: Connection refused (os error 111)WARN - gemini://lapacz-kornel.dev/git/gmnigit/ failed: IO error: failed to lookup address information: Name or service not known
WARN - Sending fatal alert BadCertificate
WARN - gemini://geminispace.info/known-hosts failed: IO error: invalid peer certificate contents: invalid peer certificate: UnsupportedCertVersionWARN - gemini://zaibatsu.circumlunar.space failed: IO error: Network is unreachable (os error 101)
WARN - gemini://heavysquare.com failed: IO error: Connection refused (os error 111)
thread '<unnamed>' panicked at 'Invalid state: BlockquoteStart', /home/shinichi/.cargo/registry/src/github.com-1ecc6299db9ec823/gmi-0.2.1/src/gemtext.rs:305:18
ERROR - gemini://carcosa.net failed@get_links() parsing page: Any { .. }
```
